language: go

go:
  - 1.8
  - tip

matrix:
  fast_finish: true
  allow_failures:
    - go: tip

sudo: required

services:
  - docker

before_install:
  - make dependencies

script:
  - make test-coverage

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - make push

deploy:
  provider: releases
  api_key:
    secure: $GITHUB_TOKEN
  file: ./build/bblfsh
  skip_cleanup: true
  on:
    tags: true
